# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddMusicWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddMusicWindow(object):
    def setupUi(self, AddMusicWindow):
        AddMusicWindow.setObjectName("AddMusicWindow")
        AddMusicWindow.resize(570, 370)
        AddMusicWindow.setMinimumSize(QtCore.QSize(570, 370))
        AddMusicWindow.setMaximumSize(QtCore.QSize(570, 370))
        AddMusicWindow.setStyleSheet("background-color: rgb(130, 130, 130);")
        self.Text_1 = QtWidgets.QLabel(AddMusicWindow)
        self.Text_1.setGeometry(QtCore.QRect(10, 20, 201, 31))
        self.Text_1.setObjectName("Text_1")
        self.InputName = QtWidgets.QLineEdit(AddMusicWindow)
        self.InputName.setGeometry(QtCore.QRect(210, 20, 331, 31))
        self.InputName.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.InputName.setObjectName("InputName")
        self.InputAuthor = QtWidgets.QLineEdit(AddMusicWindow)
        self.InputAuthor.setGeometry(QtCore.QRect(210, 110, 331, 31))
        self.InputAuthor.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.InputAuthor.setObjectName("InputAuthor")
        self.Text_2 = QtWidgets.QLabel(AddMusicWindow)
        self.Text_2.setGeometry(QtCore.QRect(10, 110, 201, 31))
        self.Text_2.setObjectName("Text_2")
        self.Text_3 = QtWidgets.QLabel(AddMusicWindow)
        self.Text_3.setGeometry(QtCore.QRect(10, 170, 191, 31))
        self.Text_3.setObjectName("Text_3")
        self.PictureFilePath = QtWidgets.QLineEdit(AddMusicWindow)
        self.PictureFilePath.setGeometry(QtCore.QRect(110, 210, 431, 31))
        self.PictureFilePath.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PictureFilePath.setObjectName("PictureFilePath")
        self.ChoosePicturePath = QtWidgets.QPushButton(AddMusicWindow)
        self.ChoosePicturePath.setGeometry(QtCore.QRect(10, 210, 93, 31))
        self.ChoosePicturePath.setObjectName("ChoosePicturePath")
        self.Ok = QtWidgets.QPushButton(AddMusicWindow)
        self.Ok.setGeometry(QtCore.QRect(350, 330, 93, 28))
        self.Ok.setObjectName("Ok")
        self.Cancel = QtWidgets.QPushButton(AddMusicWindow)
        self.Cancel.setGeometry(QtCore.QRect(460, 330, 93, 28))
        self.Cancel.setObjectName("Cancel")
        self.ChooseMusicFilePath = QtWidgets.QPushButton(AddMusicWindow)
        self.ChooseMusicFilePath.setGeometry(QtCore.QRect(10, 280, 93, 31))
        self.ChooseMusicFilePath.setObjectName("ChooseMusicFilePath")
        self.MusicFilePath = QtWidgets.QLineEdit(AddMusicWindow)
        self.MusicFilePath.setGeometry(QtCore.QRect(110, 280, 431, 31))
        self.MusicFilePath.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.MusicFilePath.setObjectName("MusicFilePath")
        self.Text_4 = QtWidgets.QLabel(AddMusicWindow)
        self.Text_4.setGeometry(QtCore.QRect(10, 250, 191, 21))
        self.Text_4.setObjectName("Text_4")

        self.retranslateUi(AddMusicWindow)
        QtCore.QMetaObject.connectSlotsByName(AddMusicWindow)

    def retranslateUi(self, AddMusicWindow):
        _translate = QtCore.QCoreApplication.translate
        AddMusicWindow.setWindowTitle(_translate("AddMusicWindow", "Dialog"))
        self.Text_1.setText(_translate("AddMusicWindow", "Input track name"))
        self.Text_2.setText(_translate("AddMusicWindow", "Input track author"))
        self.Text_3.setText(_translate("AddMusicWindow", "Add picture to track"))
        self.ChoosePicturePath.setText(_translate("AddMusicWindow", "Choose path"))
        self.Ok.setText(_translate("AddMusicWindow", "OK"))
        self.Cancel.setText(_translate("AddMusicWindow", "Cancel"))
        self.ChooseMusicFilePath.setText(_translate("AddMusicWindow", "Choose path"))
        self.Text_4.setText(_translate("AddMusicWindow", "Add file"))
