# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddPlaylistWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddPlayListWindow(object):
    def setupUi(self, AddPlayListWindow):
        AddPlayListWindow.setObjectName("AddPlayListWindow")
        AddPlayListWindow.resize(570, 370)
        AddPlayListWindow.setMinimumSize(QtCore.QSize(570, 370))
        AddPlayListWindow.setMaximumSize(QtCore.QSize(570, 370))
        AddPlayListWindow.setStyleSheet("background-color: rgb(130, 130, 130);")
        self.Text_1 = QtWidgets.QLabel(AddPlayListWindow)
        self.Text_1.setGeometry(QtCore.QRect(10, 20, 201, 31))
        self.Text_1.setObjectName("Text_1")
        self.InputName = QtWidgets.QLineEdit(AddPlayListWindow)
        self.InputName.setGeometry(QtCore.QRect(210, 20, 331, 31))
        self.InputName.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.InputName.setObjectName("InputName")
        self.InputAuthor = QtWidgets.QLineEdit(AddPlayListWindow)
        self.InputAuthor.setGeometry(QtCore.QRect(210, 110, 331, 31))
        self.InputAuthor.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.InputAuthor.setObjectName("InputAuthor")
        self.Text_2 = QtWidgets.QLabel(AddPlayListWindow)
        self.Text_2.setGeometry(QtCore.QRect(10, 110, 201, 31))
        self.Text_2.setObjectName("Text_2")
        self.Text_3 = QtWidgets.QLabel(AddPlayListWindow)
        self.Text_3.setGeometry(QtCore.QRect(10, 210, 191, 31))
        self.Text_3.setObjectName("Text_3")
        self.FilePath = QtWidgets.QLineEdit(AddPlayListWindow)
        self.FilePath.setGeometry(QtCore.QRect(110, 250, 431, 31))
        self.FilePath.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.FilePath.setObjectName("FilePath")
        self.ChoosePath = QtWidgets.QPushButton(AddPlayListWindow)
        self.ChoosePath.setGeometry(QtCore.QRect(10, 250, 93, 31))
        self.ChoosePath.setObjectName("ChoosePath")
        self.Ok = QtWidgets.QPushButton(AddPlayListWindow)
        self.Ok.setGeometry(QtCore.QRect(350, 320, 93, 28))
        self.Ok.setObjectName("Ok")
        self.Cancel = QtWidgets.QPushButton(AddPlayListWindow)
        self.Cancel.setGeometry(QtCore.QRect(460, 320, 93, 28))
        self.Cancel.setObjectName("Cancel")

        self.retranslateUi(AddPlayListWindow)
        QtCore.QMetaObject.connectSlotsByName(AddPlayListWindow)

    def retranslateUi(self, AddPlayListWindow):
        _translate = QtCore.QCoreApplication.translate
        AddPlayListWindow.setWindowTitle(_translate("AddPlayListWindow", "Dialog"))
        self.Text_1.setText(_translate("AddPlayListWindow", "Input playlist name"))
        self.Text_2.setText(_translate("AddPlayListWindow", "Input playlist author"))
        self.Text_3.setText(_translate("AddPlayListWindow", "Add picture to playlist"))
        self.ChoosePath.setText(_translate("AddPlayListWindow", "Choose path"))
        self.Ok.setText(_translate("AddPlayListWindow", "OK"))
        self.Cancel.setText(_translate("AddPlayListWindow", "Cancel"))
