# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DeletePlayListWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeletePlaylistWindow(object):
    def setupUi(self, DeletePlaylistWindow):
        DeletePlaylistWindow.setObjectName("DeletePlaylistWindow")
        DeletePlaylistWindow.resize(220, 120)
        DeletePlaylistWindow.setMinimumSize(QtCore.QSize(220, 120))
        DeletePlaylistWindow.setMaximumSize(QtCore.QSize(410, 120))
        DeletePlaylistWindow.setStyleSheet("background-color: rgb(130, 130, 130);")
        self.Ok = QtWidgets.QPushButton(DeletePlaylistWindow)
        self.Ok.setGeometry(QtCore.QRect(10, 80, 93, 28))
        self.Ok.setObjectName("Ok")
        self.Cancel = QtWidgets.QPushButton(DeletePlaylistWindow)
        self.Cancel.setGeometry(QtCore.QRect(120, 80, 93, 28))
        self.Cancel.setObjectName("Cancel")
        self.Text_1 = QtWidgets.QLabel(DeletePlaylistWindow)
        self.Text_1.setGeometry(QtCore.QRect(10, 20, 121, 31))
        self.Text_1.setObjectName("Text_1")
        self.InputName = QtWidgets.QLineEdit(DeletePlaylistWindow)
        self.InputName.setGeometry(QtCore.QRect(140, 21, 71, 31))
        self.InputName.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.InputName.setObjectName("InputName")

        self.retranslateUi(DeletePlaylistWindow)
        QtCore.QMetaObject.connectSlotsByName(DeletePlaylistWindow)

    def retranslateUi(self, DeletePlaylistWindow):
        _translate = QtCore.QCoreApplication.translate
        DeletePlaylistWindow.setWindowTitle(_translate("DeletePlaylistWindow", "Dialog"))
        self.Ok.setText(_translate("DeletePlaylistWindow", "Ok"))
        self.Cancel.setText(_translate("DeletePlaylistWindow", "Cancel"))
        self.Text_1.setText(_translate("DeletePlaylistWindow", "Input playlist number"))
